[workspace.package]
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vhrdtech/vhrd_egui"
version = "0.10.0"

[workspace]
resolver = "3"
members = [
    "ve_macro",
    "ve_widget",
    "ve_dash",
    "ve_basics",
    "ve_theme",
    "ve_template",
]

[workspace.dependencies]
egui = "0.36"
eframe = "0.36"
egui_kittest = "0.36"
erased-serde = "0.4"
typetag = "0.2"
inventory = "0.3"
tokio = { version = "1", features = ["sync"] }
