[package]
name = "ve_basics"
description = "Small egui basics every vhrd app wants: build info, non-selectable labels, hover cross-reference highlight"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
egui.workspace = true

[dev-dependencies]
egui_kittest.workspace = true
